package com.myspace.test_git;

/**
 * This class was automatically generated by the data modeler tool. A change in
 * the remote
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String cfid;

	private java.lang.String label;

	public Transaction() {
	}

	public java.lang.String getCfid() {
		return this.cfid;
	}

	public void setCfid(java.lang.String cfid) {
		this.cfid = cfid;
	}

	public java.lang.String getLabel() {
		return this.label;
	}

	public void setLabel(java.lang.String label) {
		this.label = label;
	}

	public Transaction(java.lang.String cfid, java.lang.String label) {
		this.cfid = cfid;
		this.label = label;
	}

}
