package com.myspace.test_git;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String cfid;

	public Transaction() {
	}

	public java.lang.String getCfid() {
		return this.cfid;
	}

	public void setCfid(java.lang.String cfid) {
		this.cfid = cfid;
	}

	public Transaction(java.lang.String cfid) {
		this.cfid = cfid;
	}

}